name: Release

on:
  release:
    types: [created]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn test

  publish-npm:
    name: Publish NPM
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn install
      - name: Publish package to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

#   publish-gpr:
#     name: Publish GPR
#     needs: test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 18
#           registry-url: https://npm.pkg.github.com/
#           scope: '@levibuzolic'
#         - run: yarn install
#         - run: yarn publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
