name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20, 22]
        eslint-version: [4, 5, 6, 7, 8, 9]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Biome
      run: yarn biome ci .
    - name: Tests
      run: yarn run test
      env:
        CI: true
